### ISSUE TITLE
Library does not load in Obsidan

### ISSUE THREAD

**Issue by KawaiiPotato2** [zsviczian/obsidian-excalidraw-plugin#20]
I've tried to load some libraries but no element appear in the library palette.

I did the following:

I installed the Obsidian plugin, and changed the default Excalidraw folder and Excalidraw template file folder. Then, I went to the library repository to download some of them.

I used to the library option (hotkey 9), pressed load button and opened the "excalidrawlib" file, but nothing happens , no library item appeared in the palette.

I've tried the following libraries:

- graphs.excalidrawlib
- presentation-templates.excalidrawlib
- schematic-symbols.excalidrawlib

BTW, I tried on the web too and it worked flawlessly.

**Comment by zsviczian** [comment]
What operating system are you using?
What folder name did you set? I don't think that should impact... but just trying to think out of the box to find the source of the issue.
Could you look in the .obsidian\plugins\obsidian-excalidraw-plugin folder and send me your data.json file?

**Comment by KawaiiPotato2** [comment]
The OS is Windows 10.

The Excaldraw folder is "08-Anexos/04-Excalidraw" and the Excalidraw Template file is in "10-Plantillas/Excalidraw/Template.excalidraw". Both are located within the vault's folder. The picture below shows the current configuration.

![Config](https://user-images.githubusercontent.com/59279335/116130205-3e604300-a6cb-11eb-9f17-69d22a96a6df.PNG)

[data.json.txt](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/6379217/data.json.txt)

**Comment by zsviczian** [comment]
I am trying to reproduce but still can't.
I am using Windows 10 as well. I tried your folder settings, but that all worked as expected.
Do you see any error message in console log (press ctrl+shift+i in obsidian to bring up the console log)
What version of Obsidian are you using?
What theme are you using?
Could you maybe open a blank test vault. Add only Excalidraw and see if that works?

My questions are just wild guesses trying to locate what is causing the issue.

**Comment by zsviczian** [comment]
Please test this test release. I hope to have resolved your issue:
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.6-test

**Comment by KawaiiPotato2** [comment]
My obsidian version is v0.11.13.

I've tried with a test vault and the issue persits. I'm using dark theme but I've tested other custom themes too with the same result.

I've installed obisidan and your plugin (v1.0.5) in other laptop and it is working fine, so i though the problem could be obsidian and not your plugin. I reinstalled obsidian but now the i cannot install the plugin in this laptop nor update excalidraw to the 1.06 version. I only get the message "Fail to install the plugin Excalidraw"

**Comment by zsviczian** [comment]
Sorry for the version issue. I misunderstood how community plugins check
versions... which I corrected now. You can install version 1.0.5 from
community plugins again without issues.
I'll keep looking at the library problem.

**Comment by KawaiiPotato2** [comment]
After resinstalling Obsidian and the plugin everything is working correctly. I've tested excalidraw with 3 different libraries and all of them were loaded correctly. Maybe I only need to reinstall Obsidian.

I've been wondering if there was another cause of the problem. I have every obsidian-related file in my OneDrive folder, it may sound absurd but, i have suffered problems in the past with files from other softwares that i store there, like the sudden disappearance of some files after updating them. 

I consider the issue is solved. Again, my guest is that the problem was my current installation of obsidian despite been updated to the latest version.

Thank you very much for your support, and thank a lot for the plugin

**Comment by zsviczian** [comment]
I had another similar case from another user. A reinstall of Obsidian also solved that problem.

_"So I reinstalled obsidian and installed only the 1.05 version of excalidraw as well. The stencil issue has been resolved with the new version of Obsidian. My build version was an older one but updated to 0.12.1. The stencil issue is resolved on the new dmg package version 0.11.3 and updated it to 0.12.1. So I believe the issue is related to a older build versions with an update on it. My build was I think 0.8.4 updated to 0.12.1"_

**Comment by boksir** [comment]
I am getting the same problem.. the library doesn't load in Obsidian. I am on a MacBook Pro, MacOS Version 12.3.1. 
Actually the library loaded the 1st time, but it doesn't load any more. 
I am on the latest version on Obsidian 0.14.12 and also latest on Excalidraw - 1.6.29.. I am not sure if the upgrade from 1.6.28 to .29 broke this or it is something else..
I must confess that I am new to Excalidraw, just started using it a couple of days back..

**Comment by boksir** [comment]
> I had another similar case from another user. A reinstall of Obsidian also solved that problem.
> 
> _"So I reinstalled obsidian and installed only the 1.05 version of excalidraw as well. The stencil issue has been resolved with the new version of Obsidian. My build version was an older one but updated to 0.12.1. The stencil issue is resolved on the new dmg package version 0.11.3 and updated it to 0.12.1. So I believe the issue is related to a older build versions with an update on it. My build was I think 0.8.4 updated to 0.12.1"_

I am getting the same problem.. the library doesn't load in Obsidian. I am on a MacBook Pro, MacOS Version 12.3.1.
Actually the library loaded the 1st time, but it doesn't load any more.
I am on the latest version on Obsidian 0.14.12 and also latest on Excalidraw - 1.6.29.. I am not sure if the upgrade from 1.6.28 to .29 broke this or it is something else..
I must confess that I am new to Excalidraw, just started using it a couple of days back..

**Comment by ultron** [comment]
I tried reinstalling Obsidian but that didn't resolve the issue
